import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillTwitterCircle,
} from "react-icons/ai";
import Image from "next/image";
import portrait from "../public/portrait.jpg";
import Navbar from "@/components/Navbar";
import { useState } from "react";
import darkMode from "@/components/Navbar";

export default function Home() {
  return (
    <div className="m-0 p-0">
      <Head>
        <title>Rojus Lape Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 fade-in">
        <section className="">
          <div className="text-center p-3">
            <h2 className="text-5xl py-1 dark:text-white">Rojus Lape</h2>
            <h3 className="text-2xl py-2 dark:text-white">
              Software developer
            </h3>
            <p className="dark:text-white">
              Hi! I'm Rojus Lape - an aspiring software developer currently
              pursuing a degree in Computer Science at the University of
              Freiburg.
            </p>
            <h3 className="text-center mt-5 dark:text-white">
              Read more about me
            </h3>
          </div>
          <div className="text-4xl flex gap-6 justify-center text-gray-600 dark:text-white">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className="relative rounded-full w-60 h-60 mt-10 mx-auto md:h-80 md:w-80 mb-12">
            <Image src={portrait} layout="fill" className="rounded-full" />
          </div>
        </section>
        <div></div>
      </main>
    </div>
  );
}
