import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillTwitterCircle,
} from "react-icons/ai";
import Link from "next/link";

export default function Home() {
  return (
    <div className="m-0 p-0">
      <Head>
        <title>Rojus Lape Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 fade-in">
        <section className="">
          <div className="text-center p-3 mt-24">
            <h2 className="text-5xl py-1 text-neutral-900 dark:text-white">
              Hi, my name is Rojus
            </h2>
            <p className="text-2xl font-light py-2 text-neutral-900 dark:text-white">
              Software developer
            </p>
            <p className="dark:text-white text-neutral-900"></p>
            <h3 className="font-extralight text-xl text-center  text-neutral-900 dark:text-neutral-300">
              Read more{" "}
              <Link href="/about">
                <span className="font-normal dark:text-white text-black">
                  about me
                </span>
              </Link>{" "}
              or my{" "}
              <Link href="/projects">
                <span className="font-normal dark:text-white text-black">
                  projects
                </span>
              </Link>
            </h3>
          </div>
          <div className="text-4xl flex gap-6 justify-center text-gray-600 dark:text-white">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
        </section>
        <div></div>
      </main>
    </div>
  );
}
